### PR TITLE
ci: remove an unnecessary 'os' entry

### PR DESCRIPTION
**Pull request by japaric**

### CODE REVIEW

**Comment by japaric** [comment]
@homunkulus r+

**Comment by homunkulus** [comment]
:pushpin: Commit eb8d917 has been approved by `japaric`

**Comment by homunkulus** [comment]
:hourglass: Testing commit eb8d917 with merge eb8d917...

**Comment by japaric** [comment]
@homunkulus retry

**Comment by japaric** [comment]
@homunkulus retry

**Comment by homunkulus** [comment]
:hourglass: Testing commit eb8d917 with merge eb8d917...

**Comment by japaric** [comment]
@homunkulus r-

**Comment by japaric** [comment]
@homunkulus clean

**Comment by japaric** [comment]
@homunkulus r-

**Comment by japaric** [comment]
@homunkulus r+

**Comment by homunkulus** [comment]
:pushpin: Commit bdb08bc has been approved by `japaric`

**Comment by homunkulus** [comment]
:hourglass: Testing commit bdb08bc with merge bdb08bc...

**Comment by homunkulus** [comment]
:sunny: Test successful - [travis](https://travis-ci.org/japaric/rust-cross/builds/126819906)

**Pull request merged**
